### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by douggordon2** [vipm-io/dragon-desktop-issues#29]
Unable to install Dragon. Get error:

The feed URL you are trying to reach is not available. Check to make sure the URL is correct, and that the server is running and configured to accept remote requests (https://packages.jki.net/dragon/feeds/shared/ni-labview-project-dependency-support_24.1.0.49312-0+f160_windows_x64.nipkg).

Visit ni.com/info and enter the Info Code NIPMCommError for more information.

**Comment by McGeifer** [comment]
See #25. Unfortunately their seems to be no activity from JKI.

**Comment by Tom-McQuillan** [comment]
Hello, I apologies for the lack of response. We are working on this issue now.

**Comment by Tom-McQuillan** [comment]
Hi all,

This issue has been fixed in version `2025.3.3 (build 715)` in two ways:

1. The root issue has been resolved by updating the backend technology in our Online Installer.
2. We have made the NIPKG accessible from the website directly.

> The online installer has a much smaller file size

Thanks for reporting this issue!

**Comment by McGeifer** [comment]
@Tom-McQuillan I tried to install Dragon today and still get exactly the same error? I uninstalled the old version beforehand and tried both via the package manager and directly with the .nipkg file. Both give the error as shown above.

**Comment by Tom-McQuillan** [comment]
Hi @McGeifer ,
I'm sorry to hear this, if you are willing, please could you share some details about your setup?
- If you have MAX installed, please could you send me a MAX report so I can see the NI software installed on your PC?
(following [these steps](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA03q0000019hceCAA&l=en-GB), and selecting "Technical Support Report")

**Comment by McGeifer** [comment]
@Tom-McQuillan 

Unfortunately, I now have a new PC on which LabVIEW is not installed. I am not currently programming anything with LabVIEW.
